Hw3 : main3.o printMenu.o Homework3.o
        gcc main3.o printMenu.o Homework3.o -o Hw3

Project2 : main.o printMenu.o Project2.o
        g++ main.o printMenu.o Project2.o -o Project2

main3.o : main3.c printMenu.c Homework3.c record.h main3.h
        gcc -ansi -Wall -c main3.c

main.o : main.cpp printMenu.cpp Project2.cpp record.h main.h
        g++ -ansi -Wall -c main.cpp

printMenu.o : printMenu.c
        gcc -ansi -Wall -c printMenu.c

printMenu.o : printMenu.cpp
        g++ -ansi -Wall -c printMenu.cpp

Homework3.o : Homework3.c record.h  main3.h
        gcc -ansi -Wall -c Homework3.c

Project2.o : Project2.cpp record.h main.h
        g++ -ansi -Wall -c Project2.cpp

clean :
        rm *.o Hw3
        rm *.o Project2

clean :
        rm *.o
